### PR TITLE
Updated puppetlabs/concat version requirements as versions > 4.0.1 cause errors

### PR DESCRIPTION
**Pull request by bschonec**
puppetlabs/concat > 4.0.1 results in errors when running manifests:

/etc/puppetlabs/code/environments/control/modules
├── puppet-autofs (v4.3.0)
├── puppetlabs-concat (v4.0.1)
└── puppetlabs-stdlib (v4.25.0)

[root@admin01 ~]# puppet agent -t --environment=control
Info: Using configured environment 'control'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for admin01.example.local
Info: Applying configuration version 'bc00a16f0468b13d7283c3dbdeed4f5d747f9992'
Notice: /Stage[main]/Profiles::Minimal/Autofs::Mount[proj]/Concat[/etc/auto.master]/File[/etc/auto.master]/ensure: defined content as '{md5}98b9038b157f50baf9d4917910aa390f'
Info: Concat[/etc/auto.master]: Scheduling refresh of Service[autofs]
Notice: /Stage[main]/Autofs::Service/Service[autofs]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 2.56 seconds
[root@admin01 ~]# 

Upgrade puppetlabs/concat

[root@puppetserver modules]# puppet module list --environment=control                                 
/etc/puppetlabs/code/environments/control/modules
├── puppet-autofs (v4.3.0)
├── puppetlabs-concat (v4.1.0)
└── puppetlabs-stdlib (v4.25.0)

[root@admin01 ~]# puppet agent -t --environment=control
Info: Using configured environment 'control'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'format' (file: /etc/puppetlabs/code/environments/control/modules/concat/manifests/init.pp, line: 94) on Concat_file[/etc/auto.master] (file: /etc/puppetlabs/code/environments/control/modules/concat/manifests/init.pp, line: 94) on node admin01.example.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

### CODE REVIEW

**Comment by ekohl** [comment]
Could you restart your puppetserver after upgrading? I think I've seen a similar issue where it cached incorrect versions. @alexjfisher do you recall?

**Comment by alexjfisher** [comment]
`format` is a new parameter added in [concat 4.1](https://github.com/puppetlabs/puppetlabs-concat/blob/61afe0be1e075fdc74b7581ecb3a2280b7ca4405/CHANGELOG.md#features)

Since `concat` is a native puppet type (written in ruby), you may experience [environment isolation](https://puppet.com/docs/puppet/5.4/environment_isolation.html) issues.

There are two choices.  You either use the new version of concat in all your environments (and possibly restart your puppetserver), or you use [`puppet generate types`](https://puppet.com/docs/puppet/5.4/environment_isolation.html#generate-types)

**Comment by alexjfisher** [comment]
Also see https://tickets.puppetlabs.com/browse/MODULES-5802

**Comment by dhollinger** [comment]
This is an issue with upstream issue with regards to environment isolation on the puppetserver.

We can't continue to support an older version of `concat` just because of an issue that has proven to be isolated to a subset of users (I had the issue as well).

Ended up being that restarting the `puppetserver` service solved the issue.

**Pull request closed without merging**
